# Generated by Django 6.1.1 on 2026-09-14 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('voice', models.CharField(choices=[('Soprano', 'Soprano'), ('Alto', 'Alto'), ('Tenor', 'Tenor'), ('Bass', 'Bass')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('joined_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('lyrics', models.TextField()),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='songs_audio/')),
            ],
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='choir_app.member')),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purpose', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choir_app.member')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Yaje'), ('Absent', 'Yarasibye'), ('Permission', 'Yaragize Impamvu')], max_length=15)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choir_app.member')),
            ],
        ),
    ]
