# Generated by Django 6.1.1 on 2026-09-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choir_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='purpose',
            field=models.CharField(choices=[('Uniform', "Umusanzu w'Imyenda (Uniform)"), ('Urugendo', "Umusanzu w'Ingendo (Transport)"), ('Ibirori', "Umusanzu w'Ibirori/Ubusabane"), ('Amaturo', 'Amaturo asanzwe ya Korali'), ('Ikindi', 'Ikindi kidashize ku rutonde')], max_length=50),
        ),
    ]
