# Generated by Django 6.1.1 on 2026-09-17 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choir_app', '0002_alter_contribution_purpose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='joined_date',
        ),
        migrations.RemoveField(
            model_name='song',
            name='audio_file',
        ),
        migrations.AddField(
            model_name='member',
            name='date_joined',
            field=models.DateField(auto_now_add=True, default='2026-09-17'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='photo_url',
            field=models.URLField(default='https://unsplash.com'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Yaje'), ('Absent', 'Yarasibye'), ('Permission', 'Impamvu')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leader',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choir_app.member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(default='2026-09-17', max_length=15),
            preserve_default=False,
        ),
    ]
