# Generated by Django 6.1.1 on 2026-09-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choir_app', '0003_remove_member_joined_date_remove_song_audio_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
