# Generated by Django 6.1.1 on 2026-09-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choir_app', '0004_song_audio_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribution',
            old_name='date',
            new_name='date_paid',
        ),
        migrations.RemoveField(
            model_name='member',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='member',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.RemoveField(
            model_name='song',
            name='audio_url',
        ),
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='choir_audios/'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='purpose',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='voice',
            field=models.CharField(choices=[('Soprano', 'Soprano'), ('Alto', 'Alto'), ('Tenor', 'Tenor'), ('Bass', 'Bass')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Leader',
        ),
    ]
